package com.algs.utils.file;

/**
 * All the Constant File Path is under resources/data
 */
public class FilePath {

    public static String ABAB_LZW_TXT = "data/ababLZW.txt";
    public static String BROWNIAN_TXT = "data/brownian.txt";
    public static String TINY_ST_TXT = "data/tinyST.txt";
    public static String TINY_CG_TXT = "data/tinyCG.txt";
    public static String KW1260_TXT = "data/kw1260.txt";
    public static String TINY_BATCH_TXT = "data/tinyBatch.txt";
    public static String ABRA_LZW_TXT = "data/abraLZW.txt";
    public static String ROUTES_TXT = "data/routes.txt";
    public static String TOBE_TXT = "data/tobe.txt";
    public static String TINY_FN_TXT = "data/tinyFN.txt";
    public static String TINY_TXT = "data/tiny.txt";
    public static String PI_TXT = "data/pi.txt";
    public static String RATES_TXT = "data/rates.txt";
    public static String CARDS_TXT = "data/cards.txt";
    public static String RS1423_TXT = "data/rs1423.txt";
    public static String JOBS_TXT = "data/jobs.txt";
    public static String LEIPZIG1M_TXT = "data/leipzig1M.txt";
    public static String IN2_TXT = "data/in2.txt";
    public static String IN1_TXT = "data/in1.txt";
    public static String LIST_TXT = "data/list.txt";
    public static String ABRA_TXT = "data/abra.txt";
    public static String DIFFUSION_TXT = "data/diffusion.txt";
    public static String TINY_DAG_TXT = "data/tinyDAG.txt";
    public static String MOVIES_TXT = "data/movies.txt";
    public static String MOBY_DICK_TXT = "data/mobydick.txt";
    public static String TINY_PQ_TXT = "data/tinyPQ.txt";
    public static String WORDS3_TXT = "data/words3.txt";
    public static String JOBS_PC_TXT = "data/jobsPC.txt";
    public static String UPC_CSV = "data/csv/UPC.csv";
    public static String IP_CSV = "data/csv/ip.csv";
    public static String DJIA_CSV = "data/csv/DJIA.csv";
    public static String TINY_W_TXT = "data/w/tinyW.txt";
    public static String LARGE_W_TXT = "data/w/largeW.txt";
    public static String LARGE_T_TXT = "data/t/largeT.txt";
    public static String TINY_T_TXT = "data/t/tinyT.txt";
    public static String _1_MINTS_TXT = "data/ints/1Mints.txt";
    public static String _1_KINTS_TXT = "data/ints/1Kints.txt";
    public static String _32_KINTS_TXT = "data/ints/32Kints.txt";
    public static String _4_KINTS_TXT = "data/ints/4Kints.txt";
    public static String _2_KINTS_TXT = "data/ints/2Kints.txt";
    public static String _16_KINTS_TXT = "data/ints/16Kints.txt";
    public static String _8_INTS_TXT = "data/ints/8ints.txt";
    public static String _8_KINTS_TXT = "data/ints/8Kints.txt";
    public static String Q32X48_BIN = "data/bin/q32x48.bin";
    public static String _4_RUNS_BIN = "data/bin/4runs.bin";
    public static String Q64X96_BIN = "data/bin/q64x96.bin";
    public static String M1_TXT = "data/m/m1.txt";
    public static String M2_TXT = "data/m/m2.txt";
    public static String M3_TXT = "data/m/m3.txt";
    public static String GENOME_TINY_TXT = "data/gnome/genomeTiny.txt";
    public static String GENOME_VIRUS_TXT = "data/gnome/genomeVirus.txt";
    public static String MEDIUM_UF_TXT = "data/uf/mediumUF.txt";
    public static String LARGE_UF_TXT = "data/uf/largeUF.txt";
    public static String TINY_UF_TXT = "data/uf/tinyUF.txt";
    public static String TINY_TALE_TXT = "data/tale/tinyTale.txt";
    public static String TINY_TINY_TALE_TXT = "data/tale/tinytinyTale.txt";
    public static String MED_TALE_TXT = "data/tale/medTale.txt";
    public static String TALE_TXT = "data/tale/tale.txt";
    public static String SHELLS_ST_TXT = "data/shell/shellsST.txt";
    public static String SHELLS_TXT = "data/shell/shells.txt";
    public static String EX2_TXT = "data/ex/ex2.txt";
    public static String EX1_TXT = "data/ex/ex1.txt";
    public static String EX3_TXT = "data/ex/ex3.txt";
    public static String EX4_TXT = "data/ex/ex4.txt";
    public static String LARGE_DG_TXT = "data/dg/largeDG.txt";
    public static String MEDIUM_DG_TXT = "data/dg/mediumDG.txt";
    public static String TINY_DG_TXT = "data/dg/tinyDG.txt";
    public static String TINY_EWDAG_TXT = "data/ewd/tinyEWDAG.txt";
    public static String TINY_EWDNC_TXT = "data/ewd/tinyEWDnc.txt";
    public static String TINY_EWD_TXT = "data/ewd/tinyEWD.txt";
    public static String TINY_EWDN_TXT = "data/ewd/tinyEWDn.txt";
    public static String LARGE_EWD_TXT = "data/ewd/largeEWD.txt";
    public static String MEDIUM_EWD_TXT = "data/ewd/mediumEWD.txt";
    public static String MEDIUM_EWG_TXT = "data/ewg/mediumEWG.txt";
    public static String TINY_EWG_TXT = "data/ewg/tinyEWG.txt";
    public static String LARGE_EWG_TXT = "data/ewg/largeEWG.txt";
    public static String TINY_G_TXT = "data/g/tinyG.txt";
    public static String MEDIUM_G_TXT = "data/g/mediumG.txt";
    public static String LARGE_G_TXT = "data/g/largeG.txt";
    public static String AMINO_CSV = "data/amino/amino.csv";
    public static String AMINOI_TXT = "data/amino/aminoI.txt";
    public static String AMINOI_CSV = "data/amino/aminoI.csv";

}
