package com.algs.utils.file;

/**
 * All the Constant File Path is under resources/data
 */
public class FilePath {

    public static String ABAB_LZW = "data/ababLZW.txt";
    public static String BROWNIAN = "data/brownian.txt";
    public static String TINY_ST = "data/tinyST.txt";
    public static String TINY_CG = "data/tinyCG.txt";
    public static String KW1260 = "data/kw1260.txt";
    public static String TINY_BATCH = "data/tinyBatch.txt";
    public static String ABRA_LZW = "data/abraLZW.txt";
    public static String ROUTES = "data/routes.txt";
    public static String TOBE = "data/tobe.txt";
    public static String TINY_FN = "data/tinyFN.txt";
    public static String TINY = "data/tiny.txt";
    public static String PI = "data/pi.txt";
    public static String RATES = "data/rates.txt";
    public static String CARDS = "data/cards.txt";
    public static String RS1423 = "data/rs1423.txt";
    public static String JOBS = "data/jobs.txt";
    public static String LEIPZIG1M = "data/leipzig1M.txt";
    public static String IN2 = "data/in2.txt";
    public static String IN1 = "data/in1.txt";
    public static String LIST = "data/list.txt";
    public static String ABRA = "data/abra.txt";
    public static String DIFFUSION = "data/diffusion.txt";
    public static String TINY_DAG = "data/tinyDAG.txt";
    public static String MOVIES = "data/movies.txt";
    public static String MOBY_DICK = "data/mobydick.txt";
    public static String TINY_PQ = "data/tinyPQ.txt";
    public static String WORDS3 = "data/words3.txt";
    public static String JOBS_PC = "data/jobsPC.txt";
    public static String UPC_CSV = "data/csv/UPC.csv";
    public static String IP_CSV = "data/csv/ip.csv";
    public static String DJIA_CSV = "data/csv/DJIA.csv";
    public static String TINY_W = "data/w/tinyW.txt";
    public static String LARGE_W = "data/w/largeW.txt";
    public static String LARGE_T = "data/t/largeT.txt";
    public static String TINY_T = "data/t/tinyT.txt";
    public static String INT_8 = "data/ints/8ints.txt";
    public static String INT_1K = "data/ints/1Kints.txt";
    public static String INT_2K = "data/ints/2Kints.txt";
    public static String INT_4K = "data/ints/4Kints.txt";
    public static String INT_8K = "data/ints/8Kints.txt";
    public static String INT_16K = "data/ints/16Kints.txt";
    public static String INT_32K = "data/ints/32Kints.txt";
    public static String INT_1M = "data/ints/1Mints.txt";
    public static String BIN_Q32X48 = "data/bin/q32x48.bin";
    public static String BIN_4_RUNS = "data/bin/4runs.bin";
    public static String BIN_Q64X96 = "data/bin/q64x96.bin";
    public static String M1 = "data/m/m1.txt";
    public static String M2 = "data/m/m2.txt";
    public static String M3 = "data/m/m3.txt";
    public static String GENOME_TINY = "data/gnome/genomeTiny.txt";
    public static String GENOME_VIRUS = "data/gnome/genomeVirus.txt";
    public static String MEDIUM_UF = "data/uf/mediumUF.txt";
    public static String LARGE_UF = "data/uf/largeUF.txt";
    public static String TINY_UF = "data/uf/tinyUF.txt";
    public static String TINY_TALE = "data/tale/tinyTale.txt";
    public static String TINY_TINY_TALE = "data/tale/tinytinyTale.txt";
    public static String MED_TALE = "data/tale/medTale.txt";
    public static String TALE = "data/tale/tale.txt";
    public static String SHELLS_ST = "data/shell/shellsST.txt";
    public static String SHELLS = "data/shell/shells.txt";
    public static String EX2 = "data/ex/ex2.txt";
    public static String EX1 = "data/ex/ex1.txt";
    public static String EX3 = "data/ex/ex3.txt";
    public static String EX4 = "data/ex/ex4.txt";
    public static String LARGE_DG = "data/dg/largeDG.txt";
    public static String MEDIUM_DG = "data/dg/mediumDG.txt";
    public static String TINY_DG = "data/dg/tinyDG.txt";
    public static String TINY_EWDAG = "data/ewd/tinyEWDAG.txt";
    public static String TINY_EWDNC = "data/ewd/tinyEWDnc.txt";
    public static String TINY_EWD = "data/ewd/tinyEWD.txt";
    public static String TINY_EWDN = "data/ewd/tinyEWDn.txt";
    public static String LARGE_EWD = "data/ewd/largeEWD.txt";
    public static String MEDIUM_EWD = "data/ewd/mediumEWD.txt";
    public static String MEDIUM_EWG = "data/ewg/mediumEWG.txt";
    public static String TINY_EWG = "data/ewg/tinyEWG.txt";
    public static String LARGE_EWG = "data/ewg/largeEWG.txt";
    public static String TINY_G = "data/g/tinyG.txt";
    public static String MEDIUM_G = "data/g/mediumG.txt";
    public static String LARGE_G = "data/g/largeG.txt";
    public static String AMINO_CSV = "data/amino/amino.csv";
    public static String AMINOI = "data/amino/aminoI.txt";
    public static String AMINOI_CSV = "data/amino/aminoI.csv";

}
